name: Build notebook gallery documentation using sphinx

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_docs:
    name: Build documentation
    runs-on: "ubuntu-latest"

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install mamba and create environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: doc_builder
          extra-specs: python=3.8

      - name: Install extra dependencies
        run: |
          sudo apt-get install pandoc
          python -m pip install -r extra_pip_deps.txt

      - name: Build docs
        working-directory: ./docs
        run: |
          make html
