name: Execute jupyter notebooks

env:
  # URL for the external repository linked with the notebooks in this project.
  # This repository needs to be hosted un Github
  LINKED_REPO: aperezhortal/nb_gallery_test_repo

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  run_notebooks:
    name: Execute jupyter notebooks
    runs-on: "ubuntu-latest"

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Install mamba and create environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: doc_builder
          extra-specs: python=3.8

      - name: Clone linked repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.LINKED_REPO }}
          path: ${{ env.LINKED_REPO }}

      - name: Install dependency from linked repository
        run: |
          echo "Here we should install the package"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute notebooks
        working-directory: ./docs/notebooks
        run: |
          jupyter nbconvert --to notebook --inplace --execute ./*.ipynb

      - name: Commit notebooks
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Rendering $GITHUB_SHA" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: latest
