name: Trigger notebook execution in the linked repo

########################################################################################
# Naming convention
#
# "main repository": Project repository with the python package and the documentation.
# "linked repository": Repository where the example gallery of jupyter notebooks is
#                      stored.
########################################################################################

env:
  # URL for the external repository linked with the notebooks in this project.
  # This repository needs to be hosted un Github
  LINKED_REPO: aperezhortal/nb_gallery_notebooks

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  trigger_nb_execution:
    name: Trigger the execution in the liked repo
    # The triggering is done by pushing an empty commit to the linked repository.
    # The commit message contains the Hash of the main repository's commit that
    # trigger the event.
    runs-on: "ubuntu-latest"

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Clone linked repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.LINKED_REPO }}
          path: ${{ env.LINKED_REPO }}

      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Create empty commit in linked repo
        working-directory: ${{ env.LINKED_REPO }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --allow-empty -m "Triggering nb execution from $GITHUB_SHA" \
            -m "https://github.com/aperezhortal/nb_gallery_template/commit/$GITHUB_SHA"

      - name: Push the empty commit to trigger the workflow
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ env.LINKED_REPO }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: latest
